//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdbFileManager {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdbFileManager.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string adbStartup {
            get {
                return ResourceManager.GetString("adbStartup", resourceCulture);
            }
        }

        public static string addWireless {
            get {
                return ResourceManager.GetString("addWireless", resourceCulture);
            }
        }

        public static string copy_freeze_warn {
            get {
                return ResourceManager.GetString("copy_freeze_warn", resourceCulture);
            }
        }

        public static string copy_in_progress {
            get {
                return ResourceManager.GetString("copy_in_progress", resourceCulture);
            }
        }

        public static string copy_in_progress_title {
            get {
                return ResourceManager.GetString("copy_in_progress_title", resourceCulture);
            }
        }

        public static string datagridview_attr {
            get {
                return ResourceManager.GetString("datagridview_attr", resourceCulture);
            }
        }

        public static string datagridview_date {
            get {
                return ResourceManager.GetString("datagridview_date", resourceCulture);
            }
        }

        public static string datagridview_name {
            get {
                return ResourceManager.GetString("datagridview_name", resourceCulture);
            }
        }

        public static string datagridview_size {
            get {
                return ResourceManager.GetString("datagridview_size", resourceCulture);
            }
        }

        public static string defaultDevice {
            get {
                return ResourceManager.GetString("defaultDevice", resourceCulture);
            }
        }

        public static string enterDirectoryName {
            get {
                return ResourceManager.GetString("enterDirectoryName", resourceCulture);
            }
        }

        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }

        public static string errorReportFootnote {
            get {
                return ResourceManager.GetString("errorReportFootnote", resourceCulture);
            }
        }

        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }

        public static string fileInfo {
            get {
                return ResourceManager.GetString("fileInfo", resourceCulture);
            }
        }

        public static string fromto {
            get {
                return ResourceManager.GetString("fromto", resourceCulture);
            }
        }

        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }

        public static string invalidPath {
            get {
                return ResourceManager.GetString("invalidPath", resourceCulture);
            }
        }

        public static string loadingFilesInRoot {
            get {
                return ResourceManager.GetString("loadingFilesInRoot", resourceCulture);
            }
        }

        public static string loadingProgram {
            get {
                return ResourceManager.GetString("loadingProgram", resourceCulture);
            }
        }

        public static string multipleDevicesError {
            get {
                return ResourceManager.GetString("multipleDevicesError", resourceCulture);
            }
        }

        public static string noDeviceFound {
            get {
                return ResourceManager.GetString("noDeviceFound", resourceCulture);
            }
        }

        public static string noFilesFound {
            get {
                return ResourceManager.GetString("noFilesFound", resourceCulture);
            }
        }

        public static string offline {
            get {
                return ResourceManager.GetString("offline", resourceCulture);
            }
        }

        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }

        public static string restartNeeded {
            get {
                return ResourceManager.GetString("restartNeeded", resourceCulture);
            }
        }

        public static string restartRequired {
            get {
                return ResourceManager.GetString("restartRequired", resourceCulture);
            }
        }

        public static string settings_buttonDesign {
            get {
                return ResourceManager.GetString("settings_buttonDesign", resourceCulture);
            }
        }

        public static string settings_compatibilityFix {
            get {
                return ResourceManager.GetString("settings_compatibilityFix", resourceCulture);
            }
        }

        public static string settings_darkMode {
            get {
                return ResourceManager.GetString("settings_darkMode", resourceCulture);
            }
        }

        public static string settings_darkModeNote {
            get {
                return ResourceManager.GetString("settings_darkModeNote", resourceCulture);
            }
        }

        public static string settings_fastCompatibility {
            get {
                return ResourceManager.GetString("settings_fastCompatibility", resourceCulture);
            }
        }

        public static string settings_flat {
            get {
                return ResourceManager.GetString("settings_flat", resourceCulture);
            }
        }

        public static string settings_flatShaded {
            get {
                return ResourceManager.GetString("settings_flatShaded", resourceCulture);
            }
        }

        public static string settings_fluentGradient {
            get {
                return ResourceManager.GetString("settings_fluentGradient", resourceCulture);
            }
        }

        public static string settings_iconStyle {
            get {
                return ResourceManager.GetString("settings_iconStyle", resourceCulture);
            }
        }

        public static string settings_keepFileDate {
            get {
                return ResourceManager.GetString("settings_keepFileDate", resourceCulture);
            }
        }

        public static string settings_language {
            get {
                return ResourceManager.GetString("settings_language", resourceCulture);
            }
        }

        public static string settings_openLastLocation {
            get {
                return ResourceManager.GetString("settings_openLastLocation", resourceCulture);
            }
        }

        public static string settings_previewMedia {
            get {
                return ResourceManager.GetString("settings_previewMedia", resourceCulture);
            }
        }

        public static string settings_progressSyncDelay {
            get {
                return ResourceManager.GetString("settings_progressSyncDelay", resourceCulture);
            }
        }

        public static string settings_showBackButton {
            get {
                return ResourceManager.GetString("settings_showBackButton", resourceCulture);
            }
        }

        public static string settings_tab_appearance {
            get {
                return ResourceManager.GetString("settings_tab_appearance", resourceCulture);
            }
        }

        public static string settings_tab_behaviour {
            get {
                return ResourceManager.GetString("settings_tab_behaviour", resourceCulture);
            }
        }

        public static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }

        public static string settings_twoProgressBars {
            get {
                return ResourceManager.GetString("settings_twoProgressBars", resourceCulture);
            }
        }

        public static string settings_unwrapFolders {
            get {
                return ResourceManager.GetString("settings_unwrapFolders", resourceCulture);
            }
        }

        public static string settings_useLegacyCopy {
            get {
                return ResourceManager.GetString("settings_useLegacyCopy", resourceCulture);
            }
        }

        public static string settings_windows11 {
            get {
                return ResourceManager.GetString("settings_windows11", resourceCulture);
            }
        }

        public static string settings_windowsAero {
            get {
                return ResourceManager.GetString("settings_windowsAero", resourceCulture);
            }
        }

        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }

        public static string unwrap_wait {
            get {
                return ResourceManager.GetString("unwrap_wait", resourceCulture);
            }
        }

        public static string unwrap_wait_title {
            get {
                return ResourceManager.GetString("unwrap_wait_title", resourceCulture);
            }
        }

        public static string usbDebugEnableInstructions {
            get {
                return ResourceManager.GetString("usbDebugEnableInstructions", resourceCulture);
            }
        }

        public static string wireless {
            get {
                return ResourceManager.GetString("wireless", resourceCulture);
            }
        }

        public static string wireless_enterIpPort {
            get {
                return ResourceManager.GetString("wireless_enterIpPort", resourceCulture);
            }
        }

        public static string wireless_enterPairingCode {
            get {
                return ResourceManager.GetString("wireless_enterPairingCode", resourceCulture);
            }
        }

        public static string wireless_errorOccurred {
            get {
                return ResourceManager.GetString("wireless_errorOccurred", resourceCulture);
            }
        }

        public static string wireless_ipAddress {
            get {
                return ResourceManager.GetString("wireless_ipAddress", resourceCulture);
            }
        }

        public static string wireless_pair {
            get {
                return ResourceManager.GetString("wireless_pair", resourceCulture);
            }
        }

        public static string wireless_pairingCode {
            get {
                return ResourceManager.GetString("wireless_pairingCode", resourceCulture);
            }
        }

        public static string wireless_pairingFinished {
            get {
                return ResourceManager.GetString("wireless_pairingFinished", resourceCulture);
            }
        }

        public static string wireless_port {
            get {
                return ResourceManager.GetString("wireless_port", resourceCulture);
            }
        }

        public static string wireless_reconnect {
            get {
                return ResourceManager.GetString("wireless_reconnect", resourceCulture);
            }
        }

        public static string wireless_reconnectFinished {
            get {
                return ResourceManager.GetString("wireless_reconnectFinished", resourceCulture);
            }
        }

        public static string wireless_timeout {
            get {
                return ResourceManager.GetString("wireless_timeout", resourceCulture);
            }
        }

        public static string wireless_title {
            get {
                return ResourceManager.GetString("wireless_title", resourceCulture);
            }
        }

        public static string unlock_title {
            get {
                return ResourceManager.GetString("unlock_title", resourceCulture);
            }
        }

        public static string unlock_passwordPlaceholder {
            get {
                return ResourceManager.GetString("unlock_passwordPlaceholder", resourceCulture);
            }
        }

        public static string unlock_description {
            get {
                return ResourceManager.GetString("unlock_description", resourceCulture);
            }
        }
    }
}
