//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdbFileManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdbFileManager.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting adb service. This will take a few seconds. \nPlease wait.
        /// </summary>
        public static string adbStartup {
            get {
                return ResourceManager.GetString("adbStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add wireless.
        /// </summary>
        public static string addWireless {
            get {
                return ResourceManager.GetString("addWireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even if it may not seem so at times, the files are still copying.
        ///Please do not close the program if the window freezes..
        /// </summary>
        public static string copy_freeze_warn {
            get {
                return ResourceManager.GetString("copy_freeze_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attr.
        /// </summary>
        public static string datagridview_attr {
            get {
                return ResourceManager.GetString("datagridview_attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string datagridview_date {
            get {
                return ResourceManager.GetString("datagridview_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string datagridview_name {
            get {
                return ResourceManager.GetString("datagridview_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (KiB).
        /// </summary>
        public static string datagridview_size {
            get {
                return ResourceManager.GetString("datagridview_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default device.
        /// </summary>
        public static string defaultDevice {
            get {
                return ResourceManager.GetString("defaultDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {source} to {dest}.
        /// </summary>
        public static string fromto {
            get {
                return ResourceManager.GetString("fromto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading program, please wait..
        /// </summary>
        public static string loadingProgram {
            get {
                return ResourceManager.GetString("loadingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple devices connected\nPlease disconnect other devices, or select a wanted device in dropdown thats down right..
        /// </summary>
        public static string multipleDevicesError {
            get {
                return ResourceManager.GetString("multipleDevicesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (OFFLINE).
        /// </summary>
        public static string offline {
            get {
                return ResourceManager.GetString("offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes you did require a restart to take effect..
        /// </summary>
        public static string restartNeeded {
            get {
                return ResourceManager.GetString("restartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwrapping folders.
        ///One moment please....
        /// </summary>
        public static string unwrap_wait {
            get {
                return ResourceManager.GetString("unwrap_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder unwrap.
        /// </summary>
        public static string unwrap_wait_title {
            get {
                return ResourceManager.GetString("unwrap_wait_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure USB debugging is enabled, and your device is properly connected.\nTo enable USB debugging:\n1. Go to android settings\n2. System\n3. Information about phone\n4. Find build number and click it repeatedly, until &quot;developer mode is now enabled&quot; notification\n5. go back, and find &quot;developer settings&quot;\nfind &quot;USB Debugging&quot; and enable it\n7. Enable &quot;Disable adb authorization time limit&quot;\n8. connect your phone to PC, and click authorize PC\n9. Files should now show here properly\n\nPlease note that these [rest of string was truncated]&quot;;.
        /// </summary>
        public static string usbDebugEnableInstructions {
            get {
                return ResourceManager.GetString("usbDebugEnableInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Wireless).
        /// </summary>
        public static string wireless {
            get {
                return ResourceManager.GetString("wireless", resourceCulture);
            }
        }
    }
}
